### PR TITLE
Pass the test suite with -cmodel=medany

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I don't understand why the T6_REGNUM one is necessary.

### CODE REVIEW

**Comment by kito-cheng** [comment]
Use `t6` will make cmodel=medany not work with RV32E, and just curious those pattern in pic.md is used for as/ld to generate more friendly relocation type? if not, I suggest let medany always generate load address + load or store.

**Comment by aswaterman** [comment]
I think we can get rid -mno-explicit-relocs when everything works, so t6 can go away.

**Comment by palmer-dabbelt** [comment]
@kito-cheng I think this T6 patch is actually a bug somewhere else in GCC: ideally we should be able to allocate the scratch register, right?  Did we just screw something up with the RTL pattern?

**Comment by kito-cheng** [comment]
Try this patch? https://github.com/kito-cheng/riscv-gcc/commit/cceb6df3f2e12a4ff467c92faf7388ecb9e48488

I don't run full testsuite yet, only test for 20040914-1.c since it's time to sleep in GMT+8...:P

**Comment by palmer-dabbelt** [comment]
Thanks Kito, I'll give it a run.

**Comment by kito-cheng** [comment]
@palmer-dabbelt I've seem you closs https://github.com/riscv/riscv-gnu-toolchain/issues/223, what your final patch set for this issue?

**Comment by palmer-dabbelt** [comment]
Hopefully yours, but I haven't tested it yet :)  I was just going through bugs and figured it wouldn't get lost now that there's a PR open, and I'm pretty sure it's only GCC issues.

**Comment by kito-cheng** [comment]
OK, so I continue investigate that :)

Current test suite result for `Sign/Zero extend for PIC loads` + https://github.com/kito-cheng/riscv-gcc/commit/cceb6df3f2e12a4ff467c92faf7388ecb9e48488
```
                                    |  rv32imafdc   |    rv32imac   | 
gcc       # of expected failures    |         147   |         147   | 
          # of expected passes      |       87104   |       87099   | 
          # of unexpected failures  |           3   |           3   | 
          # of unexpected successes |           3   |           3   | 
          # of unsupported tests    |        2397   |        2399   | 
g++       # of expected failures    |         318   |         318   | 
          # of expected passes      |       89563   |       89560   | 
          # of unexpected failures  |         162   |         165   | 
          # of unexpected successes |           0   |           0   | 
          # of unsupported tests    |        4615   |        4615   | 
```

**Comment by palmer-dabbelt** [comment]
Sorry, looks like I screwed up a bit.  I'm currently getting the following test failures with my fixes (in this PR)

````
+rv32ima-ilp32/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv32ima-ilp32/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
+rv32imaf-ilp32/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv32imaf-ilp32/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
+rv32imafd-ilp32d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv32imafd-ilp32d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
+rv32imafd-ilp32d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/tree-prof/time-profiler-2.c scan-ipa-dump-times profile "Read tp_first_run: 0" 2
+rv32imafd-ilp32d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/tree-prof/time-profiler-2.c scan-ipa-dump-times profile "Read tp_first_run: 2" 1
+rv32imafd-ilp32d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/tree-prof/time-profiler-2.c scan-ipa-dump-times profile "Read tp_first_run: 3" 1
+rv64ima-lp64/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv64ima-lp64/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
+rv64imaf-lp64/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv64imaf-lp64/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
+rv64imafd-lp64d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
+rv64imafd-lp64d/build-gcc-linux-stage2/gcc/testsuite/gcc/gcc.log:FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
````

I'm going to try a run of your fixes and see if it's better.

**Comment by kito-cheng** [comment]
I've try to rebase to https://github.com/riscv/riscv-gcc/commit/f9105a38249fb57f7778acf3008025f2dcac2b1f and rebuild and get pass for rv32imac, here is my branch https://github.com/kito-cheng/riscv-gcc/tree/pr65,

Test result, other config are on-going
```
                                    |    rv32imac   | 
gcc       # of expected failures    |         147   | 
          # of expected passes      |       87049   | 
          # of unexpected failures  |           1   | 
          # of unexpected successes |           2   | 
          # of unsupported tests    |        2409   | 
g++       # of expected failures    |         318   | 
          # of expected passes      |       89549   | 
          # of unexpected failures  |           0   | 
          # of unexpected successes |           0   | 
          # of unsupported tests    |        4610   | 
```

btw, I don't thing those `scan-tree-dump-not optimized` are screw up by your patch, I guess just something wrong in gcc trunk

**Comment by palmer-dabbelt** [comment]
OK, I like your fix so I'm going to take it.  I've force pushed this, if you're sure those failures are an upstream problem them I'm OK to merge.

Do you mind writing a commit message and changelog for your commit?  I don't understand what it's doing...

**Comment by palmer-dabbelt** [comment]
@kito-cheng I think your patches actually fail pr28796-2.c in rv64ima/lp64 mode.  There's some code that looks like

````
  sw a0, 8(sp)
  call
  ld a0, 8(sp)
````

which I believe is the cause of the failure.  Is it possible your patch will upgrade a load to P mode without increasing the size of the corresponding store?

**Comment by kito-cheng** [comment]
Just ack, I'm still work for this issue :)

**Comment by palmer-dabbelt** [comment]
OK, thanks.  I'm going to go ahead and submit the sign/zero PIC patch, as that actually manifests in incorrect codegen.  I'm going to leave this PR open until we have a better version of your fix for the other problem.

**Comment by palmer-dabbelt** [comment]
@kito-cheng I know you're probably busy with the RISC-V workshop, but have you had any luck with the patch?

**Comment by kito-cheng** [comment]
I'll back today :)

2017年5月11日 上午4:29，"Palmer Dabbelt" <notifications@github.com>寫道：

**Comment by kito-cheng** [comment]
updated patch which based on riscv-gcc-7 branch, include ChangeLog and some comment.
https://github.com/kito-cheng/riscv-gcc/commit/d00ed3f3e64b947a947ffefd0e4bed2129986127

And those FAIL seem cause by https://github.com/riscv/riscv-gcc/commit/2fe94d5a5a860a0226373397e05c20a873b77b4d, I think let's create a new issue for track that.
```
FAIL: gcc.dg/memmove-4.c scan-tree-dump-not optimized "memmove"
FAIL: gcc.dg/strlenopt-8.c scan-tree-dump-times strlen "memcpy \\(" 2
```

**Comment by palmer-dabbelt** [comment]
Thanks, I'm going to go run all the tests.  Do you happen to know why this is happening?  If it's just a bad RTL pattern in pic.md then I'd prefer to try and fix that instead.

**Comment by kito-cheng** [comment]
It's cause by some pass think those memory access is valid since pic.md provide patterns, and then they try to do code motion by emit move instruction (as I remember 20040914-1.c is cause by loop invariant motion), however we don't expect/consider may got non-legitimate address in move pattern before, and move pattern should never fail or emit invalid pattern.

I am not sure it's bad or not, but I don't like clobber in pattern in my personal opinion :P

**Comment by palmer-dabbelt** [comment]
Well, I don't like the clobber either -- it's really just a temporary workaround until we get the "-mexplicit-relocs" stuff working better, which should eventually be the default.  I'm just worried that there's some bigger problem in the PIC patterns and all we're doing here is just working around the bug.

This passes all the tests, and while I still don't really understand what's going on if you think it's a good patch then it works for me :).  I've merged it here, and I'll submit it upstream in a bit: https://github.com/riscv/riscv-gcc/commit/a0d67b753fc2eeaf6aca047fe80e0c4a51b9417f

Thanks!

**Pull request closed without merging**
