### PR TITLE
Update symbol name with bitmanip spec v 0.93

### PR DESCRIPTION
**Pull request by pz9115**
Update symbol name with bitmanip spec v 0.93, with ZBS class instructions and 'cpop'

Temporary annotation the 'bextw' template because it with occur an absolute expression error in gas.

Now can compile and use with the Binutils in experimental branch.

### CODE REVIEW

**Comment by kito-cheng** [comment]
> Temporary annotation the 'bextw' template because it with occur an absolute expression error in gas.

Do you mind describe this more? that sounds a binutils bug and should not work around on GCC site?

**Comment by pz9115** [comment]
> > Temporary annotation the 'bextw' template because it with occur an absolute expression error in gas.
> 
> Do you mind describe this more? that sounds a binutils bug and should not work around on GCC site?

Yes, this error is occur in assemble process,

Use GCC: https://github.com/pz9115/riscv-gcc/tree/riscv-gcc-10.2.0-rvb

and Binutils: https://github.com/pz9115/riscv-binutils-gdb/tree/riscv-binutils-experiment

When compile with 'bextw' template, it will cause an error in [tc-riscv.c L1459](https://github.com/riscv/riscv-binutils-gdb/blob/73f6b56c2d6600efe6e357ba4f4e4ae2860af221/gas/config/tc-riscv.c#L1459).

==================================

Error: instruction bextw requires absolute expression

==================================

Here is the define of 'bext' in binutils [riscv-opt.c L867](https://github.com/pz9115/riscv-binutils-gdb/blob/27c912ddf9c7172dfaa9ee39eb87076274748481/opcodes/riscv-opc.c#L867).

Maybe there is some wrong define in binutils, I'm not sure.

**Comment by kito-cheng** [comment]
I guess you fixed via this commit https://github.com/riscv/riscv-binutils-gdb/pull/255/commits/10eb40f58c6253a6ca2692da79cb8ce4d1c68da0 , so that we don't need to remove `*bextw` now?

**Comment by pz9115** [comment]
I had tested but this error still exist.

**Comment by kito-cheng** [comment]
Hmmm, let wait binutils fix first.

**Comment by pz9115** [comment]
After check the spec, found this description on page 41:

"There are non-immediate *W instructions of all single-bit instructions, including bextw, because the number of used bits in rs2 is different in bext and bextw."

So I change the rs2 args in Binutils and this problem fixed.

**Comment by kito-cheng** [comment]
Could you fix all fails?

GCC: 1d38c2503af45a27b4122bdd4f49041ec86ded25
Bintuils: d52e3ccf969016bd9db01a7e58e7902456d2c9e5
```
                === gcc: Unexpected fails for rv64gc_zba_zbb_zbc_zbs lp64d medlow ===
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-01.c scan-assembler-times addn 1
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-01.c scan-assembler-times orn 1
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-01.c scan-assembler-times xnor 1
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-02.c scan-assembler-times andn 1
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-02.c scan-assembler-times orn 1
FAIL: gcc.target/riscv/rvb-zbb-andn-orn-xorn-02.c scan-assembler-times xnor 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-01.c scan-assembler-times roli 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-01.c scan-assembler-times rori 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-02.c scan-assembler-times roli 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-02.c scan-assembler-times rori 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-03.c scan-assembler-times roliw 1
FAIL: gcc.target/riscv/rvb-zbb-rol-ror-03.c scan-assembler-times roriw 1
FAIL: gcc.target/riscv/rvb-zbb-sext-01.c scan-assembler-times sext.b 1
FAIL: gcc.target/riscv/rvb-zbb-sext-01.c scan-assembler-times sext.h 1
FAIL: gcc.target/riscv/rvb-zbb-sext-02.c scan-assembler-times sext.b 1
FAIL: gcc.target/riscv/rvb-zbb-sext-02.c scan-assembler-times sext.h 1
FAIL: gcc.target/riscv/rvb-zbbw.c scan-assembler-times pcntw 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-01.c scan-assembler-times bdep 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-01.c scan-assembler-times bext 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-02.c scan-assembler-times bdep 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-02.c scan-assembler-times bext 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-03.c scan-assembler-times bdepw 1
FAIL: gcc.target/riscv/rvb-zbe-bext-bdep-03.c scan-assembler-times bextw 1
FAIL: gcc.target/riscv/rvb-zbe-pack-packu-01.c (test for excess errors)
FAIL: gcc.target/riscv/rvb-zbe-pack-packu-02.c scan-assembler-times pack 1
FAIL: gcc.target/riscv/rvb-zbe-pack-packu-02.c scan-assembler-times packu 1
FAIL: gcc.target/riscv/rvb-zbe-pack-packu-03.c (test for excess errors)
FAIL: gcc.target/riscv/rvb-zbp-gorc-01.c scan-assembler-times gorci 1
FAIL: gcc.target/riscv/rvb-zbp-gorc-02.c scan-assembler-times gorci 1
FAIL: gcc.target/riscv/rvb-zbp-gorc-03.c scan-assembler-times gorciw 1
FAIL: gcc.target/riscv/rvb-zbp-grev-01.c scan-assembler-times grevi 1
FAIL: gcc.target/riscv/rvb-zbp-grev-02.c scan-assembler-times grevi 1
FAIL: gcc.target/riscv/rvb-zbp-grev-03.c scan-assembler-times greviw 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-01.c scan-assembler-times pack 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-01.c scan-assembler-times packh 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-01.c scan-assembler-times packu 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-02.c (test for excess errors)
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-02.c scan-assembler-times pack 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-02.c scan-assembler-times packh 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-02.c scan-assembler-times packu 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-03.c scan-assembler-times packh 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-03.c scan-assembler-times packuw 1
FAIL: gcc.target/riscv/rvb-zbp-pack-packu-packh-03.c scan-assembler-times packw 1
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-01.c (test for excess errors)
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-01.c scan-assembler-times shlfi 1
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-01.c scan-assembler-times unshlfi 1
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-02.c (test for excess errors)
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-02.c scan-assembler-times shlfi 1
FAIL: gcc.target/riscv/rvb-zbp-shfl-unshfl-02.c scan-assembler-times unshlfi 1
FAIL: gcc.target/riscv/rvb-zbp-xperm-02.c scan-assembler-times xperm_b 1
FAIL: gcc.target/riscv/rvb-zbp-xperm-02.c scan-assembler-times xperm_h 1
FAIL: gcc.target/riscv/rvb-zbp-xperm-02.c scan-assembler-times xperm_n 1
FAIL: gcc.target/riscv/rvb-zbp-xperm-02.c scan-assembler-times xperm_w 1
FAIL: gcc.target/riscv/rvb-zbs-set.c scan-assembler-times sbset 8

               ========= Summary of gcc testsuite =========
                            | # of unexpected case / # of unique unexpected case
                            |          gcc |          g++ |     gfortran |
 rv64gc_zba_zbb_zbc_zbs/  lp64d/ medlow |   54 /    27 |    0 /     0 |      - |

```

**Comment by kito-cheng** [comment]
Some of instruction are removed in zb[abc] 1.0, but it still used here, either remove those instruction or do not mixed-in version bump patch(https://github.com/riscv/riscv-gcc/pull/253/commits/1d38c2503af45a27b4122bdd4f49041ec86ded25) is fine to me.

**Comment by pz9115** [comment]
Ok, I will check it.

**Comment by pz9115** [comment]
I see that the bitmanip.md still keep pattern with v0.93, so I reset the version back into 0.93.

**Comment by kito-cheng** [comment]
Thanks!

**Pull request merged**
