### PR TITLE
Remove fpbit/dpbit/tpbit

### PR DESCRIPTION
**Pull request by aswaterman**
It seems no other architectures provide their own versions of these
files anymore, so I guess we shouldn't, either.

@kito-cheng can you verify this is the right thing to do?

### CODE REVIEW

**Comment by kito-cheng** [comment]
it's seem break RV32 soft float toolchain build

```
riscv32-unknown-linux-gnu-gcc -m32   -shared -static-libgcc -Wl,-O1 -msoft-float -Wl,-z,defs -Wl,-dynamic-linker=/lib32/ld.so.1  -B/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/csu/  -Wl,--version-script=/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc.map -Wl,-soname=libc.so.6 -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both -nostdlib -nostartfiles -e __libc_main -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32 -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/math -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/dlfcn -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nss -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nis -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/rt -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/resolv -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/crypt -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/mathvec -L/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nptl -Wl,-rpath-link=/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/math:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/dlfcn:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nss:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nis:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/rt:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/resolv:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/crypt:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/mathvec:/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/nptl -o /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc.so -T /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/shlib.lds /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/csu/abi-note.o /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf/soinit.os /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf/sofini.os /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf/interp.os /home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/elf/ld.so -lgcc
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__gettext_extract_plural':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/intl/plural-exp.c:124: undefined reference to `__subdf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/intl/plural-exp.c:141: undefined reference to `__subdf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `catopen':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:33: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:53: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:49: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:66: undefined reference to `__adddf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:101: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:97: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/catgets.c:135: undefined reference to `__adddf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__GI___open_catalog':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:41: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:41: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:41: undefined reference to `__eqdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:53: undefined reference to `__adddf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:205: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:331: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/catgets/open_catalog.c:335: undefined reference to `__eqdf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__cxa_finalize':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/cxa_finalize.c:31: undefined reference to `__subdf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `str_to_mpn':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1515: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1511: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1221: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1226: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:919: undefined reference to `__muldf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os:/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1605: more undefined references to `__muldf3' follow
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `str_to_mpn':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:993: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/strtod_l.c:1045: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `do_system':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/../sysdeps/posix/system.c:66: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdlib/../sysdeps/posix/system.c:65: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `read_int':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/vfprintf.c:1636: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/vfprintf.c:1636: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/vfprintf.c:1636: undefined reference to `__ledf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `hack_digit':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/printf_fp.c:1078: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/printf_fp.c:1085: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/printf_fp.c:1088: undefined reference to `__ledf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/printf_fp.c:1257: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__register_printf_specifier':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:43: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:51: undefined reference to `__ledf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:67: undefined reference to `__floatsidf'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:74: undefined reference to `__gedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:51: undefined reference to `__divdf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/stdio-common/reg-printf.c:71: undefined reference to `__gedf2'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__strtok_r_1c':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/string/string-inlines.c:362: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/string/string-inlines.c:462: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/string/string-inlines.c:472: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/string/string-inlines.c:465: undefined reference to `__muldf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__mbsrtowcs':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/wcsmbs/mbsrtowcs.c:29: undefined reference to `__muldf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os:/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/wcsmbs/wcschrnul.c:28: more undefined references to `__muldf3' follow
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__GI___wcscoll_l':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/wcsmbs/../string/strcoll_l.c:257: undefined reference to `__floatsidf'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/wcsmbs/../string/strcoll_l.c:261: undefined reference to `__floatsidf'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/wcsmbs/../string/strcoll_l.c:272: undefined reference to `__subdf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `fts_sort':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:687: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:693: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:851: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:851: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:136: undefined reference to `__nedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:188: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:200: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:201: undefined reference to `__nedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:208: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:220: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:231: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:144: undefined reference to `__gedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:227: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:229: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:191: undefined reference to `__gedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:131: undefined reference to `__divdf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:208: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:260: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:272: undefined reference to `__divdf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:270: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:286: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:286: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:299: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:301: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:420: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:248: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:491: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:492: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:346: undefined reference to `__nedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:443: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:465: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:484: undefined reference to `__nedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:485: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:347: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:440: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:516: undefined reference to `__gedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:526: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:540: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:521: undefined reference to `__gedf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:544: undefined reference to `__divdf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:578: undefined reference to `__unorddf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:579: undefined reference to `__gtdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/fts.c:560: undefined reference to `__divdf3'
/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc_pic.os: In function `__GI___poll':
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/../sysdeps/unix/sysv/linux/generic/poll.c:27: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/../sysdeps/unix/sysv/linux/generic/poll.c:38: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/../sysdeps/unix/sysv/linux/generic/poll.c:38: undefined reference to `__muldf3'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/../sysdeps/unix/sysv/linux/generic/poll.c:38: undefined reference to `__ltdf2'
/home/kito/riscv-workspace/riscv-gnu-toolchain/riscv-glibc/io/../sysdeps/unix/sysv/linux/generic/poll.c:38: undefined reference to `__muldf3'
collect2: error: ld returned 1 exit status
../Makerules:708: recipe for target '/home/kito/riscv-workspace/rv32i/build/build-glibc-linux32/libc.so' failed
```

**Comment by aswaterman** [comment]
Oops, I didn't try to build glibc for RV32.  I'll get that working.

**Comment by aswaterman** [comment]
In conjunction with https://github.com/riscv/riscv-glibc/commit/4a2be9674e19bc749fa81728dfab14d89598e4ff I believe this is now fixed.

**Comment by kito-cheng** [comment]
RV32IMA, RV64IMA, RV32G and RV64G is build ok and no new regression fail :)

**Comment by aswaterman** [comment]
Thanks :) I'm working on the RV32F compiler, so I'm addressing the pass/return issues we discussed a few weeks ago.

**Comment by kito-cheng** [comment]
You mean F extension but no D extension? so how the double value pass? in register fa0 and fa1 or memory?

**Comment by aswaterman** [comment]
In memory.  Passing them in fa0/fa1 makes sense in MIPS, because the ISA treats 2 32-bit registers as a 64-bit register.  But that "feature" doesn't exist in RISC-V, so it's fewer instructions to pass on the stack.

**Comment by kito-cheng** [comment]
Hmmmm, I guess we need build a ABI testsuite in some time, it's so many ABI variant with different ISA extension set.

**Comment by aswaterman** [comment]
Yeah.  To reduce the number of ABIs, we have been contemplating using the soft-float ABI for RV32F and RV64F.  Only RV32G and RV64G would use the hard-float ABI.

**Pull request merged**
