### PR TITLE
For RV32I ABIs, stack alignment should only be 64 bits

### PR DESCRIPTION
**Pull request by aswaterman**
See https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md

### CODE REVIEW

**Comment by kito-cheng** [comment]
Does this change effect to code size on RV32I since c.addi16sp may less generated?

**Comment by palmer-dabbelt** [comment]
We only require 4 byte alignment on RV32E already, so it's no change.

On Sep 7, 2017 8:17 PM, "Kito Cheng" <notifications@github.com> wrote:

Does this change effect to code size on RV32I since c.addi16sp may less
generated?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/riscv/riscv-gcc/pull/93#issuecomment-327988264>, or mute
the thread

**Comment by kito-cheng** [comment]
Yeah, but RV32I change to 8 byte alignment, not multiple of 16?

**Comment by palmer-dabbelt** [comment]
Sorry, that didn't make any sense.  I guess the point was: we're making the
same trade-off here as we do in RV32E, where we compress when possible, and
since it's a good idea there it should be here as well.

Relaxing the ABI just let's the compiler make more decisions, though you're
right that with how we do it now it'll compress less often.

**Comment by aswaterman** [comment]
However, all stack frames <= 32 bytes will still compress. That handles
functions that save up to 8 registers or have up to 8 words of stack
storage. That should be the majority.

And of course 50% of the remaining cases still compress.

**Comment by aswaterman** [comment]
BTW the compiler can still choose to over-align the stack to 16 bytes if it
wants :)

**Pull request merged**
