### PR TITLE
Work around for commit_one_edge_insertion's assertion fail

### PR DESCRIPTION
**Pull request by kito-cheng**
@aswaterman I guess you will need this work around.

### CODE REVIEW

**Comment by kito-cheng** [comment]
Relate issue for this change: https://github.com/riscv/riscv-gcc/issues/21

**Comment by aswaterman** [comment]
Maybe we should just kill riscv_block_move_loop and only do movmemsi when it's straight-line code.  Once you add the loop overhead, the cost of doing memcpy isn't so bad.

**Comment by kito-cheng** [comment]
movmemsi not only gain from the straight-line version but also gain from `inline` memcpy, so loop version is still worth to gen even it's same as memcpy function in my experiences.

**Comment by kito-cheng** [comment]
it's can save cost for function call: a jal and cost for caller save registers.

**Comment by aswaterman** [comment]
Yeah, you're right, I'll leave it alone.

**Comment by aswaterman** [comment]
The ```nop``` instruction will be killed by dead-code elimination, right?

**Comment by kito-cheng** [comment]
>The nop instruction will be killed by dead-code elimination, right?
Yes :)

**Pull request merged**
