### PR TITLE
Empty isa string

### PR DESCRIPTION
**Pull request by kito-cheng**

### CODE REVIEW

**Comment by aswaterman** [comment]
approved but will let @palmer-dabbelt merge

**Comment by palmer-dabbelt** [comment]
Whoops, I missed this.  @kito-cheng: is the first commit actually correct?  After looking at it again I think I might have just screwed up?

Either way, I'm closing #10

**Comment by kito-cheng** [comment]
@palmer-dabbelt I've fix `Treat the empty ISA string like G` without comment/author change by git rebase -i in this pull request.

**Comment by palmer-dabbelt** [comment]
Ah, OK, I get it.  I clicked the "rebase and merge" button for the first time, I believe it worked.

Thanks!

**Pull request merged**
