### PR TITLE
Refined predefined macro proposal [do not merge]

### PR DESCRIPTION
**Pull request by aswaterman**
This is a placeholder to get feedback.

### CODE REVIEW

**Comment by aswaterman** [comment]
@sorear

**Comment by sorear** [comment]
1. Why are we adding trailing underscores, I thought the agreement was to get rid of them everywhere?
2. Does `__riscv_xlen__ == 64` become the way to distinguish RV32 from RV64ILP32?
3. There are few very bad predefined macros which might be coming from somewhere else, like `_riscv` (redundant *and* not within the ANSI C reserved namespace)

**Comment by sorear** [comment]
RV32: `__riscv_xlen == 32`
RV64: `__riscv_xlen == 64 && __SIZEOF_POINTER__ == 8`
RV64 ILP32: `__riscv_xlen == 64 && __SIZEOF_POINTER__ == 4`

Viable?

(I was originally thinking we'd use `__riscv64` for this, but `__riscv_xlen` works as well.)

**Comment by aswaterman** [comment]
Makes sense to me.

**Comment by aswaterman** [comment]
Updated the PR accordingly.

**Comment by aswaterman** [comment]
This is the RV64G compiler's output now:

    #define __riscv 1
    #define __riscv_atomic 1
    #define __riscv_cmodel_medlow 1
    #define __riscv_fdiv 1
    #define __riscv_float_abi_double 1
    #define __riscv_flen 64
    #define __riscv_mul 1
    #define __riscv_muldiv 1
    #define __riscv_xlen 64
    #define __riscv_fsqrt 1
    #define __riscv_div 1

**Comment by palmer-dabbelt** [comment]
LGTM

**Pull request merged**
