### PR TITLE
Emit "i" suffix for instructions with immediate operands

### PR DESCRIPTION
**Pull request by michaeljclark**
This changes makes GCC asm output use instruction names that are consistent with the RISC-V ISA manual.

- Add 'i' letter to riscv_print_operand that prints an i character if the operand is not a register.
- Update riscv.md to add %i2 to instructions with register register and register immediate variants.

### CODE REVIEW

**Comment by aswaterman** [comment]
Moreover, is it complete?  i.e., has it passed the GCC test suite with -Wa,-mstrict-operands?

**Comment by michaeljclark** [comment]
> On 6 Jun 2017, at 8:41 AM, Andrew Waterman <notifications@github.com> wrote:
> 
> Moreover, is it complete? i.e., has it passed the GCC test suite with -Wa,-mstrict-operands?
> 

When I prepared the gcc patch I didn’t have the binutils patch applied. Has the binutils patch been merged?

If someone gives me hints on how to run the test suite with these options then I can try a run with both the gcc patch and binutils patch applied.

What target board is used when running the test suite against the GDB simulator? e.g. is this correct?

make check-gcc RUNTESTFLAGS=“--target_board=riscv-sim/-Wa,-mstrict-operands”

**Comment by aswaterman** [comment]
In the past I've just edited riscv-dejagnu/baseboards/riscv-sim.exp to add it to cflags.  Not sure about how to set it via RUNTESTFLAGS.

The patch hasn't been merged yet, and AFAIK the HEAD of binutils is unstable.  I recommend cherry-picking the -mstrict-operands patch onto the stable commit of riscv-binutils-gdb that riscv-gnu-toolchain points to.

**Comment by michaeljclark** [comment]
> On 6 Jun 2017, at 12:39 PM, Andrew Waterman <notifications@github.com> wrote:
> 
> In the past I've just edited riscv-dejagnu/baseboards/riscv-sim.exp to add it to cflags. Not sure about how to set it via RUNTESTFLAGS.
> 
> The patch hasn't been merged yet, and AFAIK the HEAD of binutils is unstable. I recommend cherry-picking the -mstrict-operands patch onto the stable commit of riscv-binutils-gdb that riscv-gnu-toolchain points to.
> 

OK. I’ll cherry-pick both patches and test with the top of riscv-gnu-toolchain when I get time…

I saw RUNTESTFLAGS here:

- https://gcc.gnu.org/install/test.html <https://gcc.gnu.org/install/test.html>

I might see if this works:

make check-gcc RUNTESTFLAGS=“--target_board=riscv-sim/-Wa,-mstrict-operands“

**Comment by aswaterman** [comment]
good luck!

**Comment by palmer-dabbelt** [comment]
Here's how I run the tests with extra options

````
riscv-gnu-toolchain $ git diff
diff --git a/Makefile.in b/Makefile.in
index 61510300c59a..d40d503da741 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -288,14 +288,14 @@ check-gcc-newlib: stamps/build-gcc-newlib-stage2
        export DEJAGNULIBS=$(srcdir)/riscv-dejagnu && \
        export RISC_V_SYSROOT=$(SYSROOT) && \
        cd build-gcc-newlib-stage2 && \
-       $(MAKE) check-gcc "RUNTESTFLAGS=--target_board=riscv-sim"
+       $(MAKE) check-gcc "RUNTESTFLAGS=--target_board=riscv-sim/-mcmodel=medany"
 
 check-gcc-linux: stamps/build-gcc-linux-stage2
        export PATH=$(srcdir)/scripts/wrapper/qemu:$(INSTALL_DIR)/bin:$(PATH) && \
        export DEJAGNULIBS=$(srcdir)/riscv-dejagnu && \
        export RISC_V_SYSROOT=$(SYSROOT) && \
        cd build-gcc-linux-stage2 && \
-       $(MAKE) check-gcc "RUNTESTFLAGS=--target_board=riscv-sim"
+       $(MAKE) check-gcc "RUNTESTFLAGS=--target_board=riscv-sim/-mcmodel=medany"
````

**Comment by michaeljclark** [comment]
When I backported the patch I noticed the riscv.md at the tip used in the current riscv-gnu-toolchain has an additional add/addw and xor pattern match. The attached patch is backported against the version of riscv-gcc in the current riscv-gnu-toolchain. Luckily the tests helped me spot this.

[riscv-gcc-strict-operands-current.patch.txt](https://github.com/riscv/riscv-gcc/files/1060068/riscv-gcc-strict-operands-current.patch.txt)

This pull has the required changes against riscv-next whereas the patch in this comment has the required change for the current riscv-gnu-toolchain, if you choose to backport it to the stable tools.

Tests pass fine! (compared against a baseline without the patch)

```
diff -u build-untouched/test.log build-strict-operands/test.log
...
@@ -273,8 +273,8 @@
 # of expected passes		91404
 # of expected failures		318
 # of unsupported tests		4582
-/home/mclark/src/riscv-gnu-toolchain/build-untouched/build-gcc-newlib-stage2/gcc/xg++  version 7.1.1 20170509 (GCC) 
+/home/mclark/src/riscv-gnu-toolchain/build-strict-operands/build-gcc-newlib-stage2/gcc/xg++  version 7.1.1 20170509 (GCC) 
```

**Comment by michaeljclark** [comment]
I also know -Wa,-mstrict-operands is working as it helped me find this (on the first run before I realised the old version of riscv-gcc has the additional patterns, and respun a new patch):

I added the backported to stable binutils patch in the comment here: https://github.com/riscv/riscv-binutils-gdb/pull/81#issuecomment-306976363

```
/tmp/ccbvanrZ.s: Assembler messages:
/tmp/ccbvanrZ.s:15373: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:15462: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:15546: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:15552: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:19994: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:20083: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:20167: Error: illegal operands `xor a4,a4,-1'
/tmp/ccbvanrZ.s:20173: Error: illegal operands `xor a4,a4,-1'
```

**Comment by michaeljclark** [comment]
So it's all good. Just make sure to use the patches in the comments if you decide to backport to stable. Or if there is a branch that corresponds to the stable version in riscv-gnu-toolchain I can make another pull request with the backports.

**Comment by aswaterman** [comment]
cool, we'll revisit after @palmer-dabbelt gets binutils back in shape

**Comment by michaeljclark** [comment]
Rogier commented that compiler explorer assembler output didn't match the ISA so I ported the strict operands patch to the gcc-7.1.0 release version and rebuilt the toolchains.

https://github.com/rv8-io/musl-riscv-toolchain/blob/master/patches/gcc-7.1-strict-operands.patch

It should apply with fuzz.

See here: https://cx.rv8.io/g/qRjxTA

**Comment by palmer-dabbelt** [comment]
Sorry for losing this last time -- I went ahead and pulled it in here for now https://github.com/riscv/riscv-gcc/commit/0e9fd0e279e4d1a43f3061dec6bebe4ff7d00a8a .  I'll try to get it upstream in a bit, but I'm afraid it might be a while as the toolchain isn't in good shape right now.

**Comment by michaeljclark** [comment]
ok. a concrete test case always helps.

what is also unfortunate is that the ABI was obviously broken going from gcc-6.1 to gcc-7.1. now you're going to have to live with this sign_extend and subreg mess in the RTL. We could always maintain a "riscv-classic" ABI i.e. circa Dec 2016. "move fast and break things".

```
$ cat > foo.c
int foo(long x) { return x; }
$ cat > main.c
#include <assert.h>
extern int foo(long x);
int main() { assert(foo(0x123456789L) == 0x23456789); }
$ /opt/riscv/toolchain-test/bin/riscv64-unknown-elf-gcc -c -O3 foo.c -o foo.o
$ /opt/riscv/toolchain-gcc-7/bin/riscv64-unknown-elf-gcc -c -O3 main.c -o main.o
$ /opt/riscv/toolchain-gcc-7/bin/riscv64-unknown-elf-gcc foo.o main.o
$ rv-sim a.out
assertion "foo(0x123456789L) == 0x23456789" failed: file "main.c", line 3, function: main
```

**Comment by michaeljclark** [comment]
oh sorry replying on the wrong bug. i was using this bug for reference on running torture.

**Comment by aswaterman** [comment]
The ABI wasn't broken from 6.1 to 7.1.  We just enforced the 32-bit canonicalization a different way: using TRULY_NOOP_TRUNCATION instead of PROMOTE_MODE.  Feedback we got during the upstreaming process led us to change the way we enforce the ABI (it didn't change the ABI).

**Comment by michaeljclark** [comment]
Theoretically, this should work without needing to change your origin. I've set my own repo as a secondary remote, so when I do a git fetch from my origin I can see my branches, but "origin" is the riscv-gcc remote:

```
git remote add michaeljclark https://github.com/michaeljclark/riscv-gcc.git
git fetch michaeljclark
git checkout --track -b riscv-gcc-7-mc michaeljclark/riscv-gcc-7-mc
```

Otherwise, it is here: https://github.com/michaeljclark/riscv-gcc/tree/riscv-gcc-7-mc

I'm going to recompile and take a look at the RTL. IIRC, it was selecting SI mode logical ops but was still emitting and not removing redundant sign_extend ops for them. This is a better situation than before as the sign_extend is deferred to the end of the function (we should see addw instead of add in the bswap.c test). We should be able to track down where this is happening, in ree.c most likely, as I think it spots elimination targets but may just punt on them if certain constraints are not met.

**Comment by michaeljclark** [comment]
There are 4 commits. You can cherry-pick the two main commits. The other two are tidying up what look like attempts at solving this issue ;-). A compiler is a complex piece of engineering!!!

**Comment by aswaterman** [comment]
Rather than use "Selectively suppress zero_extend simplification of sign_extend lshiftrt" I think we should go with my fix, which adds a (zero_extend (lshiftrt)) RTL pattern to match what they're emitting.  I don't think they will accept your middle-end patch as-is, because LOAD_EXTEND_OP isn't the right thing to use.

**Comment by michaeljclark** [comment]
Fair enough however its papering around a middle-end bug with a pattern. The optimisation is incorrect on platforms that sign extend. promote_mode isn't easily accessible in simplify-rtx because it needs a tree type. promote_mode must be used a lot earlier in GIMPLE to RTL, or however it works. If the pattern works then go for it, but the proper fix is in the middle-end, just we need to find the correct property to test.

**Comment by aswaterman** [comment]
Yeah, it's not that I like my approach... it's just that it's least disruptive.  I certainly wouldn't discourage getting it fixed your way, at which point we can kill my pattern.

**Comment by aswaterman** [comment]
Between my change, and using ```+``` instead of ```|``` to implement bswap, there are no more redundant sign-extensions.  I'm not actually seeing any cases where adding the SImode bitwise operations helps.    I took our approach from Alpha (where they only provide DImode bitwise operations to the expanders, but provide the SImode versions for combine).

Did you see any places where exposing the SImode bitwise operations to the expanders actually gets rid of sign-extension, rather than moving it around?

**Comment by michaeljclark** [comment]
I would need to look a little closer but deferring it to return value canonicalization seems like a better idea to me. It's like a bubble. If it's in one place it's easier to solve.

**Comment by michaeljclark** [comment]
Sure, if it can all be achieved with patterns in riscv.md it is an obviously lower risk option but if we are identifying middle-end issues, then we are just working around them. I'm not really fussed if the end result doesn't have the redundant sign extensions, however, I'd probably try to make the middle-end "correct".

**Comment by aswaterman** [comment]
Agreed in principle...

**Comment by michaeljclark** [comment]
If WORD_REGISTER_OPERATIONS is 1 then (ior/and/xor/not) on SI mode subregs can have their sign_extend eliminated. It's logically correct based on the fact that there is no lateral movement of bits i.e. all SI mode operations preserve canonical form. The middle-end could perhaps be taught a new trick. It might be in simplify-rtx.c or ree.c. If these operations are promoted earlier to DI mode then the proof falls apart (or I haven't thought about it for long enough).

**Comment by aswaterman** [comment]
I think it's more complicated than that, because SImode subregs aren't guaranteed to be in canonical form.

I think we need to teach REE a new trick: (and:SI (x:SI) (y: const_int with bits 31 and above clear)), or even and:DI, followed by sign_extend can eliminate the sign_extend.

**Comment by aswaterman** [comment]
(Or is that a combine?)

**Comment by michaeljclark** [comment]
I think both combine and ree call simplify-rtx.c. simplify-rtx.c appears to be the bag of tricks file :-D

**Comment by michaeljclark** [comment]
Are all SI mode ops other than (and/ior/xor/not) are *w instructions (shift,add,sub, etc) which output canonical form? (and/ior/xor/not) are logical bitwise operations that have no lateral movement in bits so bits 63:31 will all match if they have canonical input. The question is what SI mode ops can result in non-canonical form? 

The approach I'm talking about depends on there being SI mode patterns for all operations, with a proof that they maintain canonical form. (and/ior/xor/not) maintain canonical form.

Maybe we also need SI mode setcc patterns for this approach to work. I like the idea of having a proof for canonical correctness for all SI mode operations versus promoting to DI mode. Otherwise its a balloon that you press in one place and it just pops out somewhere else. ;-)

**Comment by aswaterman** [comment]
(subreg:SI (some DImode register)) is one example of something that has mode SI, but isn't canonicalized.

**Comment by aswaterman** [comment]
It would certainly be nice if SImode values were guaranteed to be canonicalized, but the only way we can enforce that is to stop using TRULY_NOOP_TRUNCATION, or else GCC's own subregs will violate the rule.  And if we take that approach, we are squeezing the balloon in a third place :)

**Comment by michaeljclark** [comment]
Hmmm. OK. It's theoretically possible to ensure they remain canonical and there is a finite set of SI mode operations. In any case, we've made some progress in our understanding of the issue and isolating its causes.

PROMOTE_MODE says "kept valid in the wider mode".

```
/* Define this macro if it is advisable to hold scalars in registers
   in a wider mode than that declared by the program.  In such cases,
   the value is constrained to be within the bounds of the declared
   type, but kept valid in the wider mode.  The signedness of the
   extension may differ from that of the type.  */
```

I can in parallel explore an option that has SI mode expansions forall ops...

**Comment by aswaterman** [comment]
Sure, but again, I'm pretty sure TRULY_NOOP_TRUNCATION will defeat your goal... it allows DImode values to be used as SImode values.  And changing TRULY_NOOP_TRUNCATION is probably a nonstarter, as changing it to the current approach was the biggest single feedback from the upstreaming process...

**Comment by aswaterman** [comment]
Let me know how it goes

**Comment by michaeljclark** [comment]
it reminds me of Alex Bradbury writing about patch review feedback in LLVM weekly news. Someone without a detailed knowledge of your architecture and ABI gives you feedback regarding your patches. i.e. someone familiar with x86 or an arch with subregister aliases like aarch64. And then you find your port has regressed in a very complicated way based on said "feedback". It seems this current setup of being passed DI mode values works well with "non canonicalised return values" (which includes DI mode). i.e. my experiment. nice simple codegen. X86 also doesn't canonicalize return values.

From the recent feedback, it seems like the port needs to do what MIPS is doing. Alpha is truly dead.  21464 was cancelled in 2001 i.e. it's a port of historical interest only. MIPS is still alive and kicking. e.g. Loongson, but mostly in China:

https://en.wikipedia.org/wiki/Loongson#Supercomputers

How does MIPS handle it? Does MIPS canonicalize return values? If it does, it's probably the most appropriate way to fix the issue despite review feedback.

**Comment by michaeljclark** [comment]
It makes me curious how to get back to the gcc-6.1 behaviour. I don't mind to have patches against mainline that won't get upstreamed. I just want nice codegen.

**Comment by aswaterman** [comment]
MIPS canonicalizes return values, too, but they accomplish it differently (with TRULY_NOOP_TRUNCATION=0 for DI->SI).

x86 is a very different case, since they have subregs in the ISA.  It's best to compare to other RISC-like architectures.

**Comment by aswaterman** [comment]
Also, 6.1 had some codegen pathologies from TRULY_NOOP_TRUNCATION=0 that are now fixed.  It's not only regressions.  We can get back to the old performance, it will just take a greater degree of understanding of the codebase than the two of us collectively possess, and probably a fair amount of hacking, too.

I wonder how this specific issue is going in LLVM.

**Comment by michaeljclark** [comment]
Yap. OK.....

LLVM only has RV32IM at present :-D riscv-gcc is significantly advanced!

**Comment by michaeljclark** [comment]
Oh it needs to canonicalize 64-bit values in pairs of registers. Actually, this is an interesting ABI test.

**Comment by michaeljclark** [comment]
Anyway, thanks for bearing with me, on my misunderstandings with respect to the ABI. I sort of need to see for myself, which we did. I've learned an incredible amount about the back-end and middle-end from looking into this issue.

**Comment by aswaterman** [comment]
It's good to not be the only one digging around in this stuff!

**Comment by michaeljclark** [comment]
I'm honestly still interested (mostly out of curiosity) in benchmarking the non-canonicalised return value variant with SI mode patterns for logical ops against riscv-gcc-6.1. It's not really fair to compare with riscv-gcc-7.1 canonical return value until its in better shape due to the TRULY_NOOP_TRUNCATION fallout.

I liken non-canonicalised return value to the "hot-potato" principle which we used in telcos to describe network routing, get the packet/value off your hands as soon as possible, and in this mode the receiver is guarded e.g. we have the sext.w in the client of int foo(long x) { return x; }

It counts as due diligence to do some metrics on that ABI variant. Wait until MS does a PE/COFF ABI with 32-bit longs and then you'll know about ABI breakage :-D

**Comment by aswaterman** [comment]
Agreed, it's not useful to make this comparison without a higher-quality implementation of the current ABI.

The intuition behind our ABI choice is that widening from int to long (e.g. using int32 in pointer arithmetic) is much more common than narrowing from long to int.  The former comes for free with the current ABI; the latter comes for free with yours.

**Comment by michaeljclark** [comment]
Your intuition is probably right.

I'm also thinking of binary translation performance. Its performance will also favor early widening of int to full-width operations. I currently have primitive eager sign extension for the 32-bit operations on RV64, and likely so does QEMU (although translation performance should never be a rationale unless it also translates to micro-architectural performance). The translator, unfortunately, can't make optimisations based on ABI assumptions. C has lots of undefined behaviours. The ISAs are kind of the opposite.

I was reasoning about a proof of SI mode operations maintaining the invariant of the upper bits without consideration that the ABI can pass non-canonical values as inputs to SI mode operands. In that case it depends on the order of operations. i.e. patterns for `(sign_extend (and|ior|xor (op:*w) (op:*w)))` and `(sign_extend (not (and|ior|xor (op:*w)))` can have their sign extension eliminated, assuming I'm now reasoning about it correctly now.

**Comment by aswaterman** [comment]
BTW I have a lead on the redundant sign-extension for ```(x >> 8) & 0xff00```.  Think of that instead as ```(x >> 8) & (0x10000 + 0xffffff00)``` because of how we generate constants in RISC-V.

If instead I try to do ```(x >> 8) & 0xf400```, which is more like ```(x >> 8) & (0xf000 + 0x400)```, the redundant sign-extension goes away.  So I think we're either emitting some non-canonical RTL in the first case, or there's a middle-end issue that's preventing optimizations because of the larger constant with more bits set, or ...who knows.  I'll continue looking into it.

**Comment by michaeljclark** [comment]
Interesting!

I noticed in some other compiler explorer that the compiler was aware of constant synthesis boundaries; in addition to the assembler. I should find that code as I have not stumbled upon it yet. I’ve seen the binutils code for li.

	- https://cx.rv8.io/g/wvMWoL

e.g.

int x() { return 0xff00ff00; }

emits:

x():
  li a0,-16711680
  addi a0,a0,-256
  ret

**Comment by aswaterman** [comment]
We want the compiler to synthesize constants, because then it can schedule the code and share the sub-pieces (e.g. it can generate 0xf001 and 0xf002 with only one LUI).  If it uses the assembler to expand LI, neither of those optimizations is possible.

**Pull request closed without merging**
