### PR TITLE
Add vector insertion and extraction functions.

### PR DESCRIPTION
**Pull request by rjiejie**
Implement vector intrinsic PR:
https://github.com/riscv/rvv-intrinsic-doc/pull/99

### CODE REVIEW

**Comment by rjiejie** [comment]
@kito-cheng Review this commit please :)

**Comment by kito-cheng** [comment]
Could you add testcase for that? I am not ask for full testcase like other [intrinsic function testcase](https://github.com/riscv/riscv-gcc/blob/riscv-gcc-10.1-rvv-dev/gcc/testsuite/gcc.target/riscv/rvv/rvv_add.c#L8), but at least one for each function call like those [testcase](https://github.com/riscv/riscv-gcc/blob/riscv-gcc-10.1-rvv-dev/gcc/testsuite/gcc.target/riscv/rvv/rvv_example5.c).

**Comment by rjiejie** [comment]
> Could you add testcase for that? I am not ask for full testcase like other [intrinsic function testcase](https://github.com/riscv/riscv-gcc/blob/riscv-gcc-10.1-rvv-dev/gcc/testsuite/gcc.target/riscv/rvv/rvv_add.c#L8), but at least one for each function call like those [testcase](https://github.com/riscv/riscv-gcc/blob/riscv-gcc-10.1-rvv-dev/gcc/testsuite/gcc.target/riscv/rvv/rvv_example5.c).

Fixed.

**Comment by rjiejie** [comment]
@kito-cheng Hello ?

**Comment by rjiejie** [comment]
@kito-cheng ping.

**Comment by rjiejie** [comment]
@kito-cheng @jim-wilson Have any comments for this commit ?

**Comment by kito-cheng** [comment]
LGTM, thanks :)

**Pull request merged**
